In [1]:
import requests
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd
import re

In [2]:
for i in range(1,31):
    url=f'https://www.flipkart.com/search?q=smartwatch&sid=ajy%2Cbuh&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&as-pos=2&as-type=HISTORY&suggestionId=smartwatch%7CSmart+Watches&requestId=0d0810b6-0413-449a-bf26-d54d847d4d52-backfill=on&page={i}'    
    page=requests.get(url)
    print(page)
    print(url)

<Response [200]>
https://www.flipkart.com/search?q=smartwatch&sid=ajy%2Cbuh&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&as-pos=2&as-type=HISTORY&suggestionId=smartwatch%7CSmart+Watches&requestId=0d0810b6-0413-449a-bf26-d54d847d4d52-backfill=on&page=1
<Response [200]>
https://www.flipkart.com/search?q=smartwatch&sid=ajy%2Cbuh&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&as-pos=2&as-type=HISTORY&suggestionId=smartwatch%7CSmart+Watches&requestId=0d0810b6-0413-449a-bf26-d54d847d4d52-backfill=on&page=2
<Response [200]>
https://www.flipkart.com/search?q=smartwatch&sid=ajy%2Cbuh&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&as-pos=2&as-type=HISTORY&suggestionId=smartwatch%7CSmart+Watches&requestId=0d0810b6-0413-449a-bf26-d54d847d4d52-backfill=on&page=3
<Response [429]>
https://www.flipkart.com/search?q=smartwatch&sid=ajy%2Cbuh&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&as-pos=2&as-type=HISTORY&suggestionId=smartwatch%7CSmart+Watches&requestId=0d0810b6-0413-449a-bf26-d54d847d4d52-backfill=on&page=4
<Response [200]>
https://www.flipkart.com/search?q=smartwatch&sid=ajy%2Cbuh&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&as-pos=2&as-type=HISTORY&suggestionId=smartwatch%7CSmart+Watches&requestId=0d0810b6-0413-449a-bf26-d54d847d4d52-backfill=on&page=5
<Response [200]>
https://www.flipkart.com/search?q=smartwatch&sid=ajy%2Cbuh&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&as-pos=2&as-type=HISTORY&suggestionId=smartwatch%7CSmart+Watches&requestId=0d0810b6-0413-449a-bf26-d54d847d4d52-backfill=on&page=6
<Response [200]>
https://www.flipkart.com/search?q=smartwatch&sid=ajy%2Cbuh&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&as-pos=2&as-type=HISTORY&suggestionId=smartwatch%7CSmart+Watches&requestId=0d0810b6-0413-449a-bf26-d54d847d4d52-backfill=on&page=7
<Response [200]>
https://www.flipkart.com/search?q=smartwatch&sid=ajy%2Cbuh&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&as-pos=2&as-type=HISTORY&suggestionId=smartwatch%7CSmart+Watches&requestId=0d0810b6-0413-449a-bf26-d54d847d4d52-backfill=on&page=8
<Response [200]>
https://www.flipkart.com/search?q=smartwatch&sid=ajy%2Cbuh&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&as-pos=2&as-type=HISTORY&suggestionId=smartwatch%7CSmart+Watches&requestId=0d0810b6-0413-449a-bf26-d54d847d4d52-backfill=on&page=9
<Response [200]>
https://www.flipkart.com/search?q=smartwatch&sid=ajy%2Cbuh&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&as-pos=2&as-type=HISTORY&suggestionId=smartwatch%7CSmart+Watches&requestId=0d0810b6-0413-449a-bf26-d54d847d4d52-backfill=on&page=10
<Response [429]>
https://www.flipkart.com/search?q=smartwatch&sid=ajy%2Cbuh&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&as-pos=2&as-type=HISTORY&suggestionId=smartwatch%7CSmart+Watches&requestId=0d0810b6-0413-449a-bf26-d54d847d4d52-backfill=on&page=11
<Response [200]>
https://www.flipkart.com/search?q=smartwatch&sid=ajy%2Cbuh&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&as-pos=2&as-type=HISTORY&suggestionId=smartwatch%7CSmart+Watches&requestId=0d0810b6-0413-449a-bf26-d54d847d4d52-backfill=on&page=12
<Response [200]>
https://www.flipkart.com/search?q=smartwatch&sid=ajy%2Cbuh&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&as-pos=2&as-type=HISTORY&suggestionId=smartwatch%7CSmart+Watches&requestId=0d0810b6-0413-449a-bf26-d54d847d4d52-backfill=on&page=13
<Response [200]>
https://www.flipkart.com/search?q=smartwatch&sid=ajy%2Cbuh&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&as-pos=2&as-type=HISTORY&suggestionId=smartwatch%7CSmart+Watches&requestId=0d0810b6-0413-449a-bf26-d54d847d4d52-backfill=on&page=14
<Response [200]>
https://www.flipkart.com/search?q=smartwatch&sid=ajy%2Cbuh&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&as-pos=2&as-type=HISTORY&suggestionId=smartwatch%7CSmart+Watches&requestId=0d0810b6-0413-449a-bf26-d54d847d4d52-backfill=on&page=15
<Response [200]>
https://www.flipkart.com/search?q=smartwatch&sid=ajy%2Cbuh&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&as-pos=2&as-type=HISTORY&suggestionId=smartwatch%7CSmart+Watches&requestId=0d0810b6-0413-449a-bf26-d54d847d4d52-backfill=on&page=16
<Response [200]>
https://www.flipkart.com/search?q=smartwatch&sid=ajy%2Cbuh&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&as-pos=2&as-type=HISTORY&suggestionId=smartwatch%7CSmart+Watches&requestId=0d0810b6-0413-449a-bf26-d54d847d4d52-backfill=on&page=17
<Response [200]>
https://www.flipkart.com/search?q=smartwatch&sid=ajy%2Cbuh&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&as-pos=2&as-type=HISTORY&suggestionId=smartwatch%7CSmart+Watches&requestId=0d0810b6-0413-449a-bf26-d54d847d4d52-backfill=on&page=18
<Response [200]>
https://www.flipkart.com/search?q=smartwatch&sid=ajy%2Cbuh&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&as-pos=2&as-type=HISTORY&suggestionId=smartwatch%7CSmart+Watches&requestId=0d0810b6-0413-449a-bf26-d54d847d4d52-backfill=on&page=19
<Response [200]>
https://www.flipkart.com/search?q=smartwatch&sid=ajy%2Cbuh&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&as-pos=2&as-type=HISTORY&suggestionId=smartwatch%7CSmart+Watches&requestId=0d0810b6-0413-449a-bf26-d54d847d4d52-backfill=on&page=20
<Response [200]>
https://www.flipkart.com/search?q=smartwatch&sid=ajy%2Cbuh&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&as-pos=2&as-type=HISTORY&suggestionId=smartwatch%7CSmart+Watches&requestId=0d0810b6-0413-449a-bf26-d54d847d4d52-backfill=on&page=21
<Response [200]>
https://www.flipkart.com/search?q=smartwatch&sid=ajy%2Cbuh&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&as-pos=2&as-type=HISTORY&suggestionId=smartwatch%7CSmart+Watches&requestId=0d0810b6-0413-449a-bf26-d54d847d4d52-backfill=on&page=22
<Response [200]>
https://www.flipkart.com/search?q=smartwatch&sid=ajy%2Cbuh&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&as-pos=2&as-type=HISTORY&suggestionId=smartwatch%7CSmart+Watches&requestId=0d0810b6-0413-449a-bf26-d54d847d4d52-backfill=on&page=23
<Response [200]>
https://www.flipkart.com/search?q=smartwatch&sid=ajy%2Cbuh&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&as-pos=2&as-type=HISTORY&suggestionId=smartwatch%7CSmart+Watches&requestId=0d0810b6-0413-449a-bf26-d54d847d4d52-backfill=on&page=24
<Response [429]>
https://www.flipkart.com/search?q=smartwatch&sid=ajy%2Cbuh&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&as-pos=2&as-type=HISTORY&suggestionId=smartwatch%7CSmart+Watches&requestId=0d0810b6-0413-449a-bf26-d54d847d4d52-backfill=on&page=25

<Response [429]>
https://www.flipkart.com/search?q=smartwatch&sid=ajy%2Cbuh&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&as-pos=2&as-type=HISTORY&suggestionId=smartwatch%7CSmart+Watches&requestId=0d0810b6-0413-449a-bf26-d54d847d4d52-backfill=on&page=26
<Response [200]>
https://www.flipkart.com/search?q=smartwatch&sid=ajy%2Cbuh&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&as-pos=2&as-type=HISTORY&suggestionId=smartwatch%7CSmart+Watches&requestId=0d0810b6-0413-449a-bf26-d54d847d4d52-backfill=on&page=27
<Response [200]>
https://www.flipkart.com/search?q=smartwatch&sid=ajy%2Cbuh&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&as-pos=2&as-type=HISTORY&suggestionId=smartwatch%7CSmart+Watches&requestId=0d0810b6-0413-449a-bf26-d54d847d4d52-backfill=on&page=28
<Response [200]>
https://www.flipkart.com/search?q=smartwatch&sid=ajy%2Cbuh&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&as-pos=2&as-type=HISTORY&suggestionId=smartwatch%7CSmart+Watches&requestId=0d0810b6-0413-449a-bf26-d54d847d4d52-backfill=on&page=29
<Response [200]>
https://www.flipkart.com/search?q=smartwatch&sid=ajy%2Cbuh&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_2_8_na_na_na&as-pos=2&as-type=HISTORY&suggestionId=smartwatch%7CSmart+Watches&requestId=0d0810b6-0413-449a-bf26-d54d847d4d52-backfill=on&page=30

In [3]:
Brand=[]
Strap=[]
Price=[]
Original_Price=[]
Discount= []
Deals=[]

for i in range(1,31):
    url='https://www.flipkart.com/search?q=smartwatch&sid=ajy%2Cbuh&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_1_8_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_1_8_na_na_na&as-pos=1&as-type=RECENT&suggestionId=smartwatch%7CSmart+Watches&requestId=0d0810b6-0413-449a-bf26-d54d847d4d52&as-backfill=on&page=20'    
    page=requests.get(url)
    soup=BeautifulSoup(page.text)
    container=soup.find_all('div' ,class_="_2B099V")
    for i in container:
        text=i.find('a' ,class_="IRpwTa")
        if text:
            Brand.append(text.text)
        else:
            Brand.append(np.nan)
            
        
        text=i.find('div' ,class_="_3I9_wc")
        if text:
            Original_Price.append(text.text)
        else:
            Original_Price.append(np.nan)
    
        
        text=i.find('div' ,class_="_3Ay6Sb")
        if text:
            Discount.append(text.text)
        else:
            Discount.append(np.nan)
            
        
        text=i.find('div',class_="_30jeq3")
        if text:
            Price.append(text.text)
        else:
            Price.append(np.nan)
        
        
        text=i.find('div' ,class_="_3eWWd-")
        if text:
            Strap.append(text)
        else:
            Strap.append(np.nan)
        
        text=i.find('div' ,class_="_2Tpdn3 _18hQoS" )
        if text:
            Deals.append(text)
        else:
            Deals.append(np.nan)

In [4]:
print(len(Brand))
print(len(Price))
print(len(Original_Price))
print(len(Discount))
print(len(Strap))

960
960
960
960
960

In [23]:
Smart_Watch={"Brand":Brand,"Price":Price,"MRP":Original_Price,"Discount":Discount,"Strap":Strap,'Deals':Deals}

In [24]:
Smart_Watch=pd.DataFrame(Smart_Watch)
df=Smart_Watch

In [25]:
Smart_Watch.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 960 entries, 0 to 959
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Brand     960 non-null    object
 1   Price     960 non-null    object
 2   MRP       960 non-null    object
 3   Discount  960 non-null    object
 4   Strap     960 non-null    object
 5   Deals     960 non-null    object
dtypes: object(6)
memory usage: 45.1+ KB

In [26]:
df=df.explode('Strap')

In [27]:
df

,Brand,Price,MRP,Discount,Strap,Deals
0,"Boult Crown 1.95'' Screen, BT Calling, Working...","₹1,399","₹4,499",68% off,"Black Strap, Free Size",[Hot Deal]
1,"Noise Qube 2 1.96"" Display with Bluetooth Call...","₹1,749","₹6,999",75% off,"Pink Strap, Regular",[Bank Offer]
2,OMNIKART T800 Ultra Smart watch with Wireless ...,₹725,"₹7,999",90% off,"Orange Strap, All",[Bank Offer]
3,SmartOne 49mm Gs Ultra 8 Extreme Clone Version...,₹785,"₹15,664",94% off,"Orange Alpine Strap, Free",[Bank Offer]
4,Ephemeral T800 ULTRA SMARTWATCH 1.9 HD DISPLAY...,₹920,"₹5,999",84% off,"Orange Strap, Free",[Bank Offer]
...,...,...,...,...,...,...
955,ULTRON ULTRONSmartwatchGOLDEN&PURPLEX6900BGB69...,"₹1,999","₹6,999",71% off,"Purple Strap, Free",[Bank Offer]
956,Ambrane Wise Eon Pro1.85 lucid display with BT...,"₹1,499","₹5,299",71% off,"Green Strap, Regular",[Daily Saver]
957,"Boult Sterling 1.52"" Rugged & Shock Proof Desi...","₹2,499","₹5,999",58% off,"Midnight Marine Strap, Free Size",[Bank Offer]
958,Like Star T800 Ultra Series 8 Watch Bluetooth ...,₹899,"₹4,999",82% off,"Orange Strap, 45",[Bank Offer]
959,Techfly T800 Ultra Watch Smartwatch Bluetooth ...,₹918,"₹5,999",84% off,"Black Strap, Free",[Bank Offer]

In [28]:
df['Size']=df['Strap'].apply(lambda x:x.split(',')[1])

In [29]:
df['color']=df['Strap'].apply(lambda x:x.split(',')[0])

In [30]:
df=df.drop('Strap',axis=1)

In [31]:
df['Price']=df['Price'].str.replace('₹','')

In [33]:
df=df.explode('Deals')

In [34]:
df

,Brand,Price,MRP,Discount,Deals,Size,color
0,"Boult Crown 1.95'' Screen, BT Calling, Working...","1,399","₹4,499",68% off,Hot Deal,Free Size,Black Strap
1,"Noise Qube 2 1.96"" Display with Bluetooth Call...","1,749","₹6,999",75% off,Bank Offer,Regular,Pink Strap
2,OMNIKART T800 Ultra Smart watch with Wireless ...,725,"₹7,999",90% off,Bank Offer,All,Orange Strap
3,SmartOne 49mm Gs Ultra 8 Extreme Clone Version...,785,"₹15,664",94% off,Bank Offer,Free,Orange Alpine Strap
4,Ephemeral T800 ULTRA SMARTWATCH 1.9 HD DISPLAY...,920,"₹5,999",84% off,Bank Offer,Free,Orange Strap
...,...,...,...,...,...,...,...
955,ULTRON ULTRONSmartwatchGOLDEN&PURPLEX6900BGB69...,"1,999","₹6,999",71% off,Bank Offer,Free,Purple Strap
956,Ambrane Wise Eon Pro1.85 lucid display with BT...,"1,499","₹5,299",71% off,Daily Saver,Regular,Green Strap
957,"Boult Sterling 1.52"" Rugged & Shock Proof Desi...","2,499","₹5,999",58% off,Bank Offer,Free Size,Midnight Marine Strap
958,Like Star T800 Ultra Series 8 Watch Bluetooth ...,899,"₹4,999",82% off,Bank Offer,45,Orange Strap
959,Techfly T800 Ultra Watch Smartwatch Bluetooth ...,918,"₹5,999",84% off,Bank Offer,Free,Black Strap

In [35]:
df['MRP']=df['MRP'].str.replace('₹','')

In [36]:
df['Discount']=df['Discount'].str.replace('% off','')

In [37]:
df['MRP']=df['MRP'].str.replace(',','')

In [38]:
df['Price']=df['Price'].str.replace(',','')

In [39]:
df

,Brand,Price,MRP,Discount,Deals,Size,color
0,"Boult Crown 1.95'' Screen, BT Calling, Working...",1399,4499,68,Hot Deal,Free Size,Black Strap
1,"Noise Qube 2 1.96"" Display with Bluetooth Call...",1749,6999,75,Bank Offer,Regular,Pink Strap
2,OMNIKART T800 Ultra Smart watch with Wireless ...,725,7999,90,Bank Offer,All,Orange Strap
3,SmartOne 49mm Gs Ultra 8 Extreme Clone Version...,785,15664,94,Bank Offer,Free,Orange Alpine Strap
4,Ephemeral T800 ULTRA SMARTWATCH 1.9 HD DISPLAY...,920,5999,84,Bank Offer,Free,Orange Strap
...,...,...,...,...,...,...,...
955,ULTRON ULTRONSmartwatchGOLDEN&PURPLEX6900BGB69...,1999,6999,71,Bank Offer,Free,Purple Strap
956,Ambrane Wise Eon Pro1.85 lucid display with BT...,1499,5299,71,Daily Saver,Regular,Green Strap
957,"Boult Sterling 1.52"" Rugged & Shock Proof Desi...",2499,5999,58,Bank Offer,Free Size,Midnight Marine Strap
958,Like Star T800 Ultra Series 8 Watch Bluetooth ...,899,4999,82,Bank Offer,45,Orange Strap
959,Techfly T800 Ultra Watch Smartwatch Bluetooth ...,918,5999,84,Bank Offer,Free,Black Strap

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 960 entries, 0 to 959
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Brand     960 non-null    object
 1   Price     960 non-null    object
 2   MRP       960 non-null    object
 3   Discount  960 non-null    object
 4   Deals     960 non-null    object
 5   Size      960 non-null    object
 6   color     960 non-null    object
dtypes: object(7)
memory usage: 60.0+ KB

In [41]:
df.to_csv('SmartWatches.csv')

In [42]:
df

,Brand,Price,MRP,Discount,Deals,Size,color
0,"Boult Crown 1.95'' Screen, BT Calling, Working...",1399,4499,68,Hot Deal,Free Size,Black Strap
1,"Noise Qube 2 1.96"" Display with Bluetooth Call...",1749,6999,75,Bank Offer,Regular,Pink Strap
2,OMNIKART T800 Ultra Smart watch with Wireless ...,725,7999,90,Bank Offer,All,Orange Strap
3,SmartOne 49mm Gs Ultra 8 Extreme Clone Version...,785,15664,94,Bank Offer,Free,Orange Alpine Strap
4,Ephemeral T800 ULTRA SMARTWATCH 1.9 HD DISPLAY...,920,5999,84,Bank Offer,Free,Orange Strap
...,...,...,...,...,...,...,...
955,ULTRON ULTRONSmartwatchGOLDEN&PURPLEX6900BGB69...,1999,6999,71,Bank Offer,Free,Purple Strap
956,Ambrane Wise Eon Pro1.85 lucid display with BT...,1499,5299,71,Daily Saver,Regular,Green Strap
957,"Boult Sterling 1.52"" Rugged & Shock Proof Desi...",2499,5999,58,Bank Offer,Free Size,Midnight Marine Strap
958,Like Star T800 Ultra Series 8 Watch Bluetooth ...,899,4999,82,Bank Offer,45,Orange Strap
959,Techfly T800 Ultra Watch Smartwatch Bluetooth ...,918,5999,84,Bank Offer,Free,Black Strap

In [43]:
df=df.astype({"Price":int,"MRP":int,"Discount":int})

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 960 entries, 0 to 959
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Brand     960 non-null    object
 1   Price     960 non-null    int32
 2   MRP       960 non-null    int32
 3   Discount  960 non-null    int32
 4   Deals     960 non-null    object
 5   Size      960 non-null    object
 6   color     960 non-null    object
dtypes: int32(3), object(4)
memory usage: 48.8+ KB

In [45]:
df.to_csv('Smart_Watches.csv',index=False)

In [46]:
df.describe(include=object)

,Brand,Deals,Size,color
count,960,960,960,960
unique,55,4,17,24
top,"Noise Qube 2 1.96"" display with Bluetooth Call...",Bank Offer,Free Size,Black Strap
freq,50,766,413,294

In [47]:
df.columns

Index(['Brand', 'Price', 'MRP', 'Discount', 'Deals', 'Size', 'color'], dtype='object')

In [48]:
df['Screen_Size']=df['Brand'].apply(lambda x: re.search(r'(\d+\.\d+)', x).group(1) if re.search(r'(\d+\.\d+)', x) else None)

In [49]:
df['Company']=df['Brand'].apply(lambda x: re.search(r'^([^\d]+)', x).group(1).strip())

In [50]:
df

,Brand,Price,MRP,Discount,Deals,Size,color,Screen_Size,Company
0,"Boult Crown 1.95'' Screen, BT Calling, Working...",1399,4499,68,Hot Deal,Free Size,Black Strap,1.95,Boult Crown
1,"Noise Qube 2 1.96"" Display with Bluetooth Call...",1749,6999,75,Bank Offer,Regular,Pink Strap,1.96,Noise Qube
2,OMNIKART T800 Ultra Smart watch with Wireless ...,725,7999,90,Bank Offer,All,Orange Strap,None,OMNIKART T
3,SmartOne 49mm Gs Ultra 8 Extreme Clone Version...,785,15664,94,Bank Offer,Free,Orange Alpine Strap,None,SmartOne
4,Ephemeral T800 ULTRA SMARTWATCH 1.9 HD DISPLAY...,920,5999,84,Bank Offer,Free,Orange Strap,1.9,Ephemeral T
...,...,...,...,...,...,...,...,...,...
955,ULTRON ULTRONSmartwatchGOLDEN&PURPLEX6900BGB69...,1999,6999,71,Bank Offer,Free,Purple Strap,None,ULTRON ULTRONSmartwatchGOLDEN&PURPLEX
956,Ambrane Wise Eon Pro1.85 lucid display with BT...,1499,5299,71,Daily Saver,Regular,Green Strap,1.85,Ambrane Wise Eon Pro
957,"Boult Sterling 1.52"" Rugged & Shock Proof Desi...",2499,5999,58,Bank Offer,Free Size,Midnight Marine Strap,1.52,Boult Sterling
958,Like Star T800 Ultra Series 8 Watch Bluetooth ...,899,4999,82,Bank Offer,45,Orange Strap,None,Like Star T
959,Techfly T800 Ultra Watch Smartwatch Bluetooth ...,918,5999,84,Bank Offer,Free,Black Strap,None,Techfly T

In [51]:
df.drop('Brand',axis=1)

,Price,MRP,Discount,Deals,Size,color,Screen_Size,Company
0,1399,4499,68,Hot Deal,Free Size,Black Strap,1.95,Boult Crown
1,1749,6999,75,Bank Offer,Regular,Pink Strap,1.96,Noise Qube
2,725,7999,90,Bank Offer,All,Orange Strap,None,OMNIKART T
3,785,15664,94,Bank Offer,Free,Orange Alpine Strap,None,SmartOne
4,920,5999,84,Bank Offer,Free,Orange Strap,1.9,Ephemeral T
...,...,...,...,...,...,...,...,...
955,1999,6999,71,Bank Offer,Free,Purple Strap,None,ULTRON ULTRONSmartwatchGOLDEN&PURPLEX
956,1499,5299,71,Daily Saver,Regular,Green Strap,1.85,Ambrane Wise Eon Pro
957,2499,5999,58,Bank Offer,Free Size,Midnight Marine Strap,1.52,Boult Sterling
958,899,4999,82,Bank Offer,45,Orange Strap,None,Like Star T
959,918,5999,84,Bank Offer,Free,Black Strap,None,Techfly T

In [52]:
df.to_csv('Cleaned_Smart_Watches.csv',index=False)